[% BLOCK backend_jsinclude %]
<style>
    #incdocs_desk_status {
        padding-top: 20px;
        display: none;
    }
    .incdocs_desk_transaction {
        display: flex;
    }
    .incdocs_desk_transaction > * {
        width: 25%;
    }
    #transactions_header {
        font-weight: 700;
        margin-bottom: 0.5rem;
    }
    #incdocs_desk_header {
        margin-bottom: 1rem;
    }
</style>
[% END %]